# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'

[shell]
disabled = false
nu_indicator = '[n](bold green)u'
elvish_indicator = '[󰘧](bold green)'

[jobs]
style = 'bold yellow'

[package]
disabled = true

[cmd_duration]
disabled = true
min_time=10_000

[directory]
truncation_symbol = '…/'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = ''

[git_status]
modified = 'M'

[rust]
# format = '[$symbol($version )]($style)'
format = '[$symbol]($style)'

[python]
format = '[$symbol]($style)'

[scala]
disabled = true
format = '[$symbol]($style)'
symbol = ''

[java]
format = '[JVM]($style)'
#symbol = ''

[lua]
format = 'via [$symbol]($style)'

[haskell]
format = 'via [$symbol]($style)'

# Redundant modules
[aws]
disabled = true

[azure]
disabled = true

[gcloud]
disabled = true

[terraform]
disabled = true

[vcs]
disabled = true

[vcsh]
disabled = true

