# theme = "varua"
theme = "github_dark_dimmed"

[editor]
mouse = false
cursorline = true
cursorcolumn = true
end-of-line-diagnostics = "hint"
bufferline = "multiple"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.file-picker]
hidden = false

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'

[editor.indent-guides]
render = true

[editor.auto-save]
after-delay.enable = false

[keys.normal.space]
e = [
  ':sh rm -f /tmp/unique-file-h21a434',
  ':insert-output yazi "%{buffer_name}" --chooser-file=/tmp/unique-file-h21a434',
  ':sh printf "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file-h21a434}',
  ':redraw',
]

